import { ChartType } from './default.model';
const companyType = [
  {
    id: 1,
    type: 'Industry',
  },
  {
    id: 2,
    type: 'Subindustry',
  },
];
const leadSourceArray = [
  { id: 1, lead: 'Website' },
  { id: 2, lead: 'Direct Sales' },
  { id: 3, lead: 'Internal Reference' },
  { id: 4, lead: 'Business Development Partner' },
]

const cstatusArray = [
  { id: 1, status: 'Active'},
  { id: 2, status: 'Inactive' },
  { id: 3, status: 'Dormant' },
  { id: 4, status: 'Do Not Call' },
];
const expertLeadSourceArray = [
  { id: 1, lead: 'Self Sourced' },
  { id: 2, lead: 'Refferal' },
  { id: 3, lead: 'Web Signup' },
  { id: 4, lead: 'Campaign Signup' },
];
const stageStatus = [
  { id: 1, stage: 'Contacted' },
  { id: 2, stage: 'Interested' },
  { id: 3, stage: 'In Progress' },
 // { id: 5, stage: 'Client' },
];
const countryArray = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'land Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'AndorrA', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People'S Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montenegro', code: 'ME' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'RWANDA', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];
const stateArray = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttarakhand',
  'Uttar Pradesh',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Delhi',
  'Lakshadweep',
  'Puducherry',
];

const incentiveChartData: ChartType = {
  series: [
    {
      name: 'BTC',
      data: [12, 14, 2, 47, 42, 15, 47, 75, 65, 19, 14],
    },
  ],
  chart: {
    type: 'area',
    height: 40,
    sparkline: {
      enabled: true,
    },
  },
  stroke: {
    curve: 'smooth',
    width: 2,
  },
  colors: ['#50a5f1'],
  fill: {
    type: 'gradient',
    gradient: {
      shadeIntensity: 1,
      inverseColors: false,
      opacityFrom: 0.45,
      opacityTo: 0.05,
      stops: [25, 100, 100, 100],
    },
  },
  tooltip: {
    fixed: {
      enabled: false,
    },
    x: {
      show: false,
    },
    marker: {
      show: false,
    },
  },
};
const dummyData = {
  id: 0,
  companyName: 'Congizant LTD',
  companyType: 0,
  contactNo: '+919019326282',
  email: 'abyys@gmail.com',
  fax: 'string',
  address: 'string',
  city: 'string',
  state: 'string',
  country: 'string',
  zipCode: 'string',
  leadStatus: 0,
  labels: 'string',
  assigneeId: 0,
  createdBy: 0,
  updatedBy: 0,
  deletedBy: 0,
  createdAt: '2020-09-26T14:41:35.137Z',
  updatedAt: '2020-09-26T14:41:35.137Z',
  deletedAt: '2020-09-26T14:41:35.137Z',
  salesOwner: '',
  leadSource: '2',
  leadReference: '2',
  referenceIncentiveType: 1,
  referenceIncentive: '220',
  leadIntroduction: 1,
  introductionIncentiveType: 1,
  introductionIncentive: '10',
  leadAssignee: 1,
  assigneeIncentiveType: 1,
  assigneeIncentive: '120',
  timeZone: '5:30 GMT',
  lastContacted: '2020-09-26T14:41:35.137Z',
  leadContactId: 1,
};
const salesLeadContactData = {
  id: 1,
  name: 'string',
  email: 'string@gmail.com',
  designation: 'designation',
  contactNo: 988997898,
  alternateMobile: 8768876897,
  notes: 'string',
  createdBy: 1,
  updatedBy: 2,
  updatedAt: '2020-09-26T14:41:35.137Z',
  createdAt: '2020-09-26T14:41:35.137Z',
  deletedBy: 2,
  deletedAt: '2020-09-26T14:41:35.137Z',
  lastContacted: '2020-09-26T14:41:35.137Z',
};
const users = [
  { id: 1, name: 'Praveer' },
  { id: 2, name: 'Shubham' },
  { id: 3, name: 'Pranav' },
  { id: 4, name: 'Rahul' },
  { id: 5, name: 'Vinit' },
  { id: 6, name: 'Sumit' },
];

const stageStatusDisplay = ['', 'Contacted', 'Interested', 'In Progress', 'Client', 'Not Interested', 'Do Not Call'];

const countryCurrency = [
  { currency: 'AED', country: 'United Arab Emirates Dirham' },
  { currency: 'AFN', country: 'Afghan Afghani' },
  { currency: 'AMD', country: 'Albanian Lek' },
  { currency: 'AWG', country: 'Aruban Florin' },
  { currency: 'IDR', country: 'Indonesian Rupiah' },
  { currency: 'ILS', country: 'Israeli New Sheqel' },
  { currency: 'IMP', country: 'Manx pound' },
  { currency: 'INR', country: 'Indian Rupee' },
  { currency: 'IQD', country: 'Iraqi Dinar' },
  { currency: 'IRR', country: 'Iranian Rial' },
  { currency: 'ISK', country: 'Icelandic Króna' },
  { currency: 'JEP', country: 'Jersey Pound' },
  { currency: 'RSD', country: 'Serbian Dinar' },
  { currency: 'RUB', country: 'Russian Ruble' },
  { currency: 'RWF', country: 'Rwandan Franc' },
  { currency: 'TWD', country: 'New Taiwan Dollar' },
  { currency: 'UAH', country: 'Ukrainian Hryvnia' },
  { currency: 'USD', country: 'United States Dollar' },
  { currency: 'UYU', country: 'Uruguayan Peso' },
  { currency: 'ZWL', country: 'Zimbabwean Dollar' },
];
const billingCycleArray = ['Monthly', 'Quarterly', 'Half Yearly', 'Yearly'];

const EmailJsTemplates = {
  salesleadSaved: 'template_amvv772',
  salesleadUpdated: 'template_dummy',
  BDPsaved: 'template_4381zee',
  BDPupdated: 'template_dummy',
  BDPattached: 'template_dummy',
  statusChangeToClient: 'template_ympgtc3', //status change to client
  clientProfile: 'template_w12gy08',
  complianceRequest: 'template_dummy',
  complianceRequestEmail: 'template_f634bcc',
  MSAupdated: 'template_4wpsf2t',
  clientusers: 'template_dummy',
  experUpdated: 'template_p7nyp4g',
  experUpdatedBank: 'template_0ank35h',
  experEventComplete: 'template_qoyukji',
  project: 'template_dummy',
  ProjectUpdate: 'template_dummy',
  expertToGTAM: 'template_tucmhee',
  NewEvent: 'template_tcdjkob',

  eventReschedule: 'template_dummy',
  eventCancelled: 'template_dummy',
  eventCompleted: 'template_gteb56x',

  Invoicegenerated: 'template_gteb56x', //both client & expert
  clientInvoicePaid: 'template_dummy',
  expertInvoicePaid: 'template_dummy',

  sendInvitation: 'template_x116mgp',
};
const EmailTitleDescription = {
  salesleadSaved: { title: 'SHERPA | Sales notification alert ', description: 'Sales lead saved successfully' },
  BDPsaved: { title: 'SHERPA | Sales notification alert ', description: 'BDP User saved successfully' },
  BDPAttached: { title: 'SHERPA | Sales notification alert ', description: 'BDP attached to sales lead successfully' },
  statusChangeToClient: { title: 'SHERPA | Client notification alert', description: '' },
  clientProfile: { title: 'SHERPA | Client notification alert ', description: 'MSA details updated successfully' },
  complianceRequest: { title: 'SHERPA | Client notification alert ', description: 'MSA details updated successfully' },
  complianceRequestEmail: {
    title: 'SHERPA | Client notification alert ',
    description: 'MSA details updated successfully',
  },
  project: { title: 'SHERPA | Project notification alert ', description: 'New project created successfully' },
  Projectupdate: { title: 'SHERPA | Project notification alert ', description: 'Project updated successfully' },
  ProjectExperts: {
    title: 'SHERPA | Project notification alert ',
    description: 'Expert attached to the projectsuccessfully',
  },
  LeadstoExpert: {
    title: 'SHERPA | Project notification alert ',
    description: 'Lead converted to expert successfully',
  },
  ExpertPortal: { title: 'SHERPA | Project notification alert ', description: 'Expert updated successfully' },
  ExperttoGTAM: { title: 'SHERPA | Project notification alert ', description: 'GTAM Submitted successfully' },
  NewEvent: { title: 'SHERPA | Event notification alert ', description: 'New event created successfully' },
  EventisReschedule: { title: 'SHERPA | Event notification alert ', description: 'Event rescheduled successfully' },
  EventisCancel: { title: 'SHERPA | Event notification alert ', description: 'Event cancelled successfully' },
  completedchangestatus: { title: 'SHERPA | Event notification alert ', description: 'Event completed successfully' },
  Failedchangestatus: { title: 'SHERPA | Event notification alert ', description: 'Event creation falied' },
  Invoicegenerated: {
    title: 'SHERPA | Accounting - notification alert',
    description: 'Invoice generated successfully',
  },
  Invoicepaid: { title: 'SHERPA | Accounting - notification alert ', description: 'Invoice Paid successfully' },

  salesleadUpdated: { title: 'SHERPA | Sales notification alert ', description: 'Sales lead updated successfully' },

  BDPupdated: { title: 'SHERPA | Sales notification alert ', description: 'BDP updaTed successfully' },
  BDPattached: { title: 'SHERPA | Sales notification alert ', description: 'BDP attached successfully' },

  MSAupdated: { title: 'SHERPA | Client notification alert ', description: 'MSA updated successfully' },
  clientusers: { title: 'SHERPA | Client notification alert ', description: 'Client user created successfully' },
  experUpdated: { title: 'SHERPA | Project notification alert ', description: 'Expert updated successfully' },

  expertToGTAM: { title: 'SHERPA | Project notification alert ', description: 'Expert transfer to GTAM successfully' },

  eventReschedule: { title: 'SHERPA | Event notification alert ', description: 'Event Reschedule successfully' },
  eventCancelled: { title: 'SHERPA | Event notification alert ', description: 'Event Cancelled successfully' },
  eventCompleted: { title: 'SHERPA | Event notification alert ', description: 'Event Completed successfully' },

  clientInvoicePaid: { title: 'SHERPA | Accounting - notification alert ', description: 'Invoice Paid successfully' },
  expertInvoicePaid: { title: 'SHERPA | Accounting - notification alert ', description: 'Invoice Paid successfully' },

  sendInvitation: { title: 'SHERPA | Event notification alert ', description: 'Invitation Send successfully' },
};

export {
  companyType,
  leadSourceArray,
  countryArray,
  stateArray,
  incentiveChartData,
  dummyData,
  salesLeadContactData,
  stageStatus,
  stageStatusDisplay,
  billingCycleArray,
  countryCurrency,
  EmailJsTemplates,
  expertLeadSourceArray,
  EmailTitleDescription,
  cstatusArray
};
