const krexpert = {
  id: '3asd5642r545sfssdfsd5646545',
  firstName: 'Roger',
  lastName: 'Johnson',
  primaryEmail: 'rogerjohnson@gmail.com',
  status: 'Contacted',
  currentEmployer: 'ABC Company',
  designation: 'Sr. Software Engineer',
  contactNo: '+91 80556 55645',
  state: 'Tamil Nadu',
  industry: 'Banking',
  krRelationshipMgr: 'Amit Kubade',
  rate: '5000',
  currency: 'INR',
  rateType: 'Hourly',
  terms: true,
  isLead: false,
};

const krexperts = {
  leadsAttached: [
    {
      id: '3asd5642r545sfssdfsd5646545',
      firstName: 'Roger',
      lastName: 'Johnson',
      primaryEmail: 'rogerjohnson@gmail.com',
      contactNo: '+91 80556 55645',
      status: 'Contacted',
      currentEmployer: 'ABC Company',
      designation: 'Sr. Project Manager',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      isLead: false,
    },
    {
      id: '3asd5642r545sfssdfsd5646546',
      firstName: 'One',
      lastName: 'Johnson',
      primaryEmail: 'rogerjohnson@gmail.com',
      contactNo: '+91 80556 55645',
      status: 'Recruting in Progress',
      currentEmployer: 'X Corp.',
      designation: 'Joint Director',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      terms: false,
      isLead: true,
    },
    {
      id: '3asd5642r545sfssdfsd5646547',
      firstName: 'Two',
      lastName: 'Johnson',
      primaryEmail: 'rogerjohnson@gmail.com',
      contactNo: '+91 80556 55645',
      status: 'Recruited',
      currentEmployer: 'ZPixel Co.',
      designation: 'Founder',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      terms: true,
      isLead: false,
    },
    {
      id: '3asd5642r545sfssdfsd5646548',
      firstName: 'Three',
      lastName: 'Johnson',
      primaryEmail: 'rogerjohnson@gmail.com',
      contactNo: '+91 80556 55645',
      status: 'T&C Done',
      currentEmployer: 'IRS Tech',
      designation: 'Sr. Finance Manager',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      terms: false,
      isLead: true,
    },
    {
      id: '3asd5642r545sfssdfsd5646549',
      firstName: 'Four',
      lastName: 'Johnson',
      primaryEmail: 'rogerjohnson@gmail.com',
      contactNo: '+91 80556 55645',
      status: 'T&C Pending',
      currentEmployer: 'Volvo Cars India Pvt Ltd',
      designation: 'Sr. Finance Manager',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      terms: false,
      isLead: true,
    },
  ],

  givenToAccMgr: [
    {
      id: '3asd5642r545sfssdfsd5646548',
      firstName: 'Three',
      lastName: 'Johnson',
      primaryEmail: 'rogerjohnson@gmail.com',
      contactNo: '+91 80556 55645',
      status: 'T&C Done',
      currentEmployer: 'IRS Tech',
      designation: 'Sr. Finance Manager',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      terms: false,
      isLead: false,
    },
    {
      id: '3asd5642r545sfssdfsd5646549',
      firstName: 'Four',
      lastName: 'Johnson',
      primaryEmail: 'rogerjohnson@gmail.com',
      contactNo: '+91 80556 55645',
      status: 'T&C Pending',
      currentEmployer: 'Volvo Cars India Pvt Ltd',
      designation: 'Sr. Finance Manager',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      terms: true,
      isLead: false,
    },
    {
      id: '3asd5642r545sfssdfsd5646550',
      firstName: 'Five',
      lastName: 'Johnson',
      primaryEmail: 'fivejohnson@gmail.com',
      contactNo: '+91 80556 59650',
      status: 'T&C Pending',
      currentEmployer: 'Volvo Cars India Pvt Ltd',
      designation: 'Sr. Finance Manager',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      terms: true,
      isLead: false,
    },
  ],

  givenToClient: [
    {
      id: '3asd5642r545sfssdfsd5646548',
      firstName: 'Three',
      lastName: 'Johnson',
      primaryEmail: 'rogerjohnson@gmail.com',
      contactNo: '+91 80556 55645',
      status: 'T&C Done',
      currentEmployer: 'IRS Tech',
      designation: 'Sr. Finance Manager',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      terms: true,
      isLead: false,
    },
    {
      id: '3asd5642r545sfssdfsd5646549',
      firstName: 'Four',
      lastName: 'Johnson',
      primaryEmail: 'rogerjohnson@gmail.com',
      contactNo: '+91 80556 55645',
      status: 'T&C Done',
      currentEmployer: 'Volvo Cars India Pvt Ltd',
      designation: 'Sr. Finance Manager',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      terms: true,
      isLead: false,
    },
    {
      id: '3asd5642r545sfssdfsd5646550',
      firstName: 'Five',
      lastName: 'Johnson',
      primaryEmail: 'fivejohnson@gmail.com',
      contactNo: '+91 80556 59650',
      status: 'T&C Done',
      currentEmployer: 'Volvo Cars India Pvt Ltd',
      designation: 'Sr. Finance Manager',
      state: 'Tamil Nadu',
      industry: 'Banking',
      krRelationshipMgr: 'Amit Kubade',
      rate: '5000',
      currency: 'INR',
      rateType: 'Hourly',
      terms: true,
      isLead: false,
    },
  ],
};

const krExpertsList = [
  {
    id: '3asd5642r545sfssdfsd5646548',
    firstName: 'Three',
    lastName: 'Johnson',
    primaryEmail: 'rogerjohnson@gmail.com',
    contactNo: '+91 80556 55645',
    status: 'T&C Done',
    currentEmployer: 'IRS Tech',
    designation: 'Sr. Finance Manager',
    state: 'Tamil Nadu',
    industry: 'Banking',
    krRelationshipMgr: 'Amit Kubade',
    rate: '5000',
    currency: 'INR',
    rateType: 'Hourly',
    terms: false,
    isLead: false,
  },
  {
    id: '3asd5642r545sfssdfsd5646549',
    firstName: 'Four',
    lastName: 'Johnson',
    primaryEmail: 'rogerjohnson@gmail.com',
    contactNo: '+91 80556 55645',
    status: 'T&C Pending',
    currentEmployer: 'Volvo Cars India Pvt Ltd',
    designation: 'Sr. Finance Manager',
    state: 'Tamil Nadu',
    industry: 'Banking',
    krRelationshipMgr: 'Amit Kubade',
    rate: '5000',
    currency: 'INR',
    rateType: 'Hourly',
    terms: true,
    isLead: false,
  },
  {
    id: '3asd5642r545sfssdfsd5646550',
    firstName: 'Five',
    lastName: 'Johnson',
    primaryEmail: 'fivejohnson@gmail.com',
    contactNo: '+91 80556 59650',
    status: 'T&C Pending',
    currentEmployer: 'Volvo Cars India Pvt Ltd',
    designation: 'Sr. Finance Manager',
    state: 'Tamil Nadu',
    industry: 'Banking',
    krRelationshipMgr: 'Amit Kubade',
    rate: '5000',
    currency: 'INR',
    rateType: 'Hourly',
    terms: true,
    isLead: false,
  },
];

export { krexpert, krexperts, krExpertsList };
