const EntityDetails = [
  {
    id: 1,
    name: 'APAC ',
    displayName: 'Knowledgeridge Sherpa',
    address: 'Delhi',
    bankName: 'HDFC Bank',
    bankAccountName: 'Knowledgeridge Sherpa',
    branch: 'Pawan Nagar',
    accountNo: '342156878909',
    ifscCode: 'HDFCB0003421',
    otherDetails: '',
  },
  {
    id: 2,
    name: 'EMEA',
    displayName: 'Knowledgeridge',
    address: 'Mumbai',
    bankName: 'ICICI Bank',
    bankAccountName: 'Knowledgeridge',
    branch: 'Shivaji Nagar',
    accountNo: '9087564332113',
    ifscCode: 'ICICB0009087',
    otherDetails: '',
  },
  {
    id: 23,
    name: 'AMERICAS ',
    displayName: 'Knowledgeridge',
    address: 'Mumbai',
    bankName: 'ICICI Bank',
    bankAccountName: 'Knowledgeridge',
    branch: 'Shivaji Nagar',
    accountNo: '9087564332113',
    ifscCode: 'ICICB0009087',
    otherDetails: '',
  },
];

export { EntityDetails };
